const roles = [
  {period:'MAY 2025 — MAY 2026',title:{en:'Senior Software Developer',es:'Senior Software Developer'},company:'British Airways',location:{en:'Remote',es:'Remoto'},sector:{en:'AVIATION · BIG DATA · AI',es:'AVIACIÓN · BIG DATA · IA'},summary:{en:'Took an internal flight-scheduling efficiency MVP to a stable release, building the functionality needed to score and compare different models.',es:'Llevé un MVP de eficiencia en el cálculo de horarios de vuelos hasta una versión estable, desarrollando lo necesario para puntuar y comparar distintos modelos.'},bullets:{en:['Improved communication between microservices and the use of FastAPI.','Moved the API towards an internal domain-driven design (DDD) architecture and modelled the domain.','Improved test coverage and created a CI system.','Built client modules for connections to other services.','Optimised ETL workflows with Dagster to make them clearer, scalable and easier to monitor.','Contributed to frontend features alongside backend and data engineering work.'],es:['Mejoré la comunicación entre microservicios y el uso de FastAPI.','Orienté la API hacia una arquitectura interna basada en DDD e hice modelado de dominio.','Mejoré la cobertura de pruebas y creé un sistema de CI.','Desarrollé módulos cliente para conectar con otros servicios.','Optimicé flujos ETL con Dagster para hacerlos más claros, escalables y fáciles de monitorizar.','También contribuí a funcionalidades de frontend junto al trabajo backend y de ingeniería de datos.']},stack:['Python','FastAPI','React · frontend','Dagster','Docker','Microservices · DDD','Automated testing · CI']},
  {period:'NOV 2021 — MAY 2024',title:{en:'Lead Backend Engineer',es:'Lead Backend Engineer'},company:'Idoven',location:{en:'Remote',es:'Remoto'},sector:{en:'HEALTHCARE · AI · BIG DATA',es:'SALUD · IA · BIG DATA'},summary:{en:'Led the new backend version for a cardiology technology platform focused on early detection and precision medicine. Its AI-powered ECG system works with one of the world’s largest ECG datasets.',es:'Lideré la nueva versión del backend de una plataforma de tecnología médica centrada en la detección temprana y la medicina de precisión. Su sistema de ECG basado en IA trabaja con una de las mayores bases de datos de ECG del mundo.'},bullets:{en:['Helped recruit the backend team through screening, interviews and technical exercises.','Defined the product roadmap in close collaboration with Product and the CTO.','Designed and built a new API version from the ground up, including technology selection and implementation.','Implemented tests and continuous integration; managed permissions, authentication and authorisation.','Documented APIs with OpenAPI/Swagger and integrated external APIs and the frontend.','Introduced agile practices with Jira and Scrum, and established team coding standards.'],es:['Participé en la selección del equipo backend mediante entrevistas y pruebas técnicas.','Definí el roadmap del producto junto al equipo de producto y el CTO.','Diseñé y construí desde cero una nueva versión de la API, incluida la selección tecnológica.','Implanté pruebas e integración continua; gestioné permisos, autenticación y autorización.','Documenté las APIs con OpenAPI/Swagger e integré APIs externas y el frontend.','Implanté prácticas ágiles con Jira y Scrum y definí estándares de código del equipo.']},stack:['REST APIs','OpenAPI · Swagger','Authentication · permissions','External API integration','Automated testing · CI','Jira · Scrum']},
  {period:'DEC 2020 — NOV 2021',title:{en:'Lead Backend Developer',es:'Lead Backend Developer'},company:'Kado Networks',location:{en:'Remote',es:'Remoto'},sector:{en:'NETWORKING',es:'NETWORKING'},summary:{en:'Led backend development for a digital business-card platform designed to make professional contact management more intuitive.',es:'Lideré el desarrollo backend de una plataforma de tarjetas de visita digitales para hacer más intuitiva la gestión de contactos profesionales.'},bullets:{en:['Defined the product roadmap with Product and the CTO.','Designed and built the system API from initial technology choices to implementation.','Implemented tests and continuous integration.','Managed user and system permissions, authentication and authorisation.','Documented the API with OpenAPI/Swagger and integrated external APIs.'],es:['Definí el roadmap del producto junto al equipo de producto y el CTO.','Diseñé y construí la API desde la selección tecnológica inicial hasta su implementación.','Implanté pruebas e integración continua.','Gestioné permisos, autenticación y autorización de usuarios y sistemas.','Documenté la API con OpenAPI/Swagger e integré APIs externas.']},stack:['REST APIs','OpenAPI · Swagger','Authentication · permissions','External API integration','Automated testing · CI','Jira · Scrum']},
  {period:'FEB 2020 — JAN 2021',title:{en:'Lead Backend Developer',es:'Lead Backend Developer'},company:'Xfera Consumer Finance',location:{en:'Remote',es:'Remoto'},sector:{en:'FINTECH',es:'FINTECH'},summary:{en:'First development hire and backend lead for a hybrid payment institution distributing consumer credit, personal loans and credit cards through the MásMóvil network.',es:'Primer desarrollador y lead backend de una entidad de pago híbrida dedicada al crédito al consumo, préstamos personales y tarjetas de crédito a través de la red de MásMóvil.'},bullets:{en:['Recruited the backend team through interviews and technical exercises.','Started the API from scratch, defining and implementing infrastructure and technology choices.','Introduced tests and continuous integration.','Managed permissions across systems and documented APIs with Swagger.','Integrated external APIs and introduced agile practices with Jira and Scrum.'],es:['Seleccioné al equipo backend mediante entrevistas y pruebas técnicas.','Inicié la API desde cero, definiendo e implantando la infraestructura y las tecnologías.','Introduje pruebas e integración continua.','Gestioné permisos entre sistemas y documenté las APIs con Swagger.','Integré APIs externas e implanté prácticas ágiles con Jira y Scrum.']},stack:['REST APIs','Swagger · OpenAPI','System permissions','External API integration','Automated testing · CI','Jira · Scrum']},
  {period:'FEB 2019 — JAN 2020',title:{en:'Senior Backend Developer',es:'Senior Backend Developer'},company:'Savana Médica',location:{en:'Madrid (Spain)',es:'Madrid (España)'},sector:{en:'HEALTHCARE · AI · BIG DATA',es:'SALUD · IA · BIG DATA'},summary:{en:'Led the application backend at a medical AI company analysing millions of clinical cases to support medical research and healthcare decisions.',es:'Lideré el backend del área de aplicaciones en una empresa de IA médica que analizaba millones de casos clínicos para apoyar la investigación y las decisiones sanitarias.'},bullets:{en:['Built the main system’s new API and moved the product towards SaaS using DDD.','Created a back-office API to centralise internal tools.','Maintained and improved the system, adding features and fixing issues.','Improved the reading and detection algorithm.','Migrated user access control to Amazon Cognito and managed permissions.','Worked closely with Product using weekly sprints, Jira and Scrum.','Introduced testing and continuous integration; documented APIs with Swagger and integrated external APIs.'],es:['Creé la nueva API del sistema principal y lo llevé hacia SaaS usando DDD.','Desarrollé una API de back-office para centralizar herramientas internas.','Mantuve y mejoré el sistema, incorporando funcionalidades y resolviendo errores.','Mejoré el algoritmo de lectura y detección.','Migré el control de acceso de usuarios a Amazon Cognito y gestioné permisos.','Colaboré con producto en sprints semanales, Jira y Scrum.','Implanté pruebas e integración continua, documenté APIs con Swagger e integré APIs externas.']},stack:['Amazon Cognito','REST APIs · Swagger','DDD · SaaS','User permissions','Automated testing · CI','Jira · Scrum']},
  {period:'NOV 2017 — FEB 2019',title:{en:'Senior Backend Developer',es:'Senior Backend Developer'},company:'StyleSage',location:{en:'Madrid (Spain)',es:'Madrid (España)'},sector:{en:'RETAIL · AI · BIG DATA',es:'RETAIL · IA · BIG DATA'},summary:{en:'Built backend systems for an AI-powered retail analytics platform covering pricing, assortment, promotions and trends for global brands.',es:'Desarrollé sistemas backend para una plataforma de analítica retail basada en IA, con información sobre precios, surtido, promociones y tendencias.'},bullets:{en:['Created APIs, token-based access and permissions for internal systems.','Introduced weekly agile sprints, Jira, Kanban and regular reviews.','Added tests and API documentation; built a repository of internal libraries.','Integrated Google Cloud, Gmail API and OpenExchangeRates.','Set up AWS instances, web services and workers.','Implemented a step-based email and screenshot processing system using queues.'],es:['Creé APIs, acceso mediante tokens y permisos para sistemas internos.','Puse en marcha sprints semanales, Jira, Kanban y reuniones periódicas.','Añadí pruebas y documentación de APIs y creé un repositorio de librerías internas.','Integré Google Cloud, Gmail API y OpenExchangeRates.','Preparé instancias en AWS y configuré servicios web y workers.','Implementé un sistema por etapas para procesar emails y capturas mediante colas.']},stack:['AWS · Google Cloud','Gmail API · OpenExchangeRates','REST APIs · tokens','Queues · workers','Internal libraries','Automated testing · Jira · Kanban']},
  {period:'JAN 2016 — SEP 2017',title:{en:'Backend Developer',es:'Backend Developer'},company:'Jinn',location:{en:'London (UK)',es:'Londres (Reino Unido)'},sector:{en:'ON-DEMAND DELIVERY',es:'DELIVERY A DOMICILIO'},summary:{en:'Developed the backend for a London-based on-demand delivery platform operating in the UK and Spain.',es:'Desarrollé el backend de una plataforma londinense de reparto a domicilio bajo demanda, activa en Reino Unido y España.'},bullets:{en:['Built and maintained server features and APIs designed for high demand and scalability.','Internationalised the app to support additional languages.','Integrated SendGrid for email and improved notification and SMS systems.','Improved the testing structure and supported reliable releases.'],es:['Desarrollé y mantuve funcionalidades de servidor y APIs preparadas para alta demanda y escalabilidad.','Internacionalicé la aplicación para añadir idiomas.','Integré SendGrid para email y mejoré los sistemas de notificaciones y SMS.','Mejoré la estructura de pruebas y apoyé entregas fiables.']},stack:['Python','Backend APIs','SendGrid','Notifications · SMS','Internationalisation','Automated testing']},
  {period:'JAN 2015 — MAY 2016',title:{en:'Software Developer · Python Tester',es:'Software Developer · Tester Python'},company:'Novastone Media',location:{en:'London (UK)',es:'Londres (Reino Unido)'},sector:{en:'MESSAGING · SECURITY',es:'MENSAJERÍA · SEGURIDAD'},summary:{en:'Software development and Python testing for a company building secure, mobile-focused platforms for financial services.',es:'Desarrollo de software y pruebas en Python en una empresa de plataformas seguras orientadas a móvil para servicios financieros.'},bullets:{en:['Worked as a software developer and Python tester.'],es:['Trabajé en desarrollo de software y pruebas con Python.']},stack:['Python','Software testing']},
  {period:'MAR 2011 — FEB 2013',title:{en:'IT Specialist · Software Developer',es:'Informático · Desarrollo de software'},company:'Instituto Nacional de Técnica Aeroespacial (INTA)',location:{en:'Huelva (Spain)',es:'Huelva (España)'},sector:{en:'AEROSPACE · GIS',es:'AEROESPACIAL · GIS'},summary:{en:'Developed applications in the radar department, taking part in the full software lifecycle from requirements and design to implementation, installation and testing.',es:'Desarrollé aplicaciones en el departamento de radares, participando en todo el ciclo de software: requisitos, diseño, implementación, implantación y pruebas.'},bullets:{en:['Programmed microcontrollers and real-time applications.','Worked with GIS applications, Ethernet communications, USB and RS-232 ports, and communications with UAVs and drones.'],es:['Programé microcontroladores y aplicaciones en tiempo real.','Trabajé con aplicaciones GIS, comunicaciones Ethernet, puertos USB y RS-232 y comunicaciones con VANT y drones.']},stack:['Java','MySQL · phpMyAdmin','Windows · Eclipse · NetBeans','GIS','Real-time systems','Ethernet · USB · RS-232']},
  {period:'JAN 2010 — JUL 2010',title:{en:'Final Degree Project · Biomedical NLP',es:'Proyecto fin de carrera · NLP biomédico'},company:'University of Huelva',location:{en:'Huelva (Spain)',es:'Huelva (España)'},sector:{en:'RESEARCH · NLP',es:'INVESTIGACIÓN · NLP'},summary:{en:'Built a desktop application to support extractive summarisation and create gold-standard datasets for evaluating automatic biomedical text summarisation.',es:'Desarrollé una aplicación de escritorio para apoyar la creación de resúmenes extractivos y generar conjuntos Gold Standard para evaluar la generación automática de resúmenes biomédicos.'},bullets:{en:['Preprocessed text, identified language and biomedical concepts, split text into sentences and visualised concept frequency.','The project supported corpus creation and evaluation of automatic summarisation.'],es:['Preprocesaba el texto, identificaba el idioma y conceptos biomédicos, dividía el texto en frases y mostraba la frecuencia de los conceptos.','El proyecto servía de apoyo para crear corpus y evaluar sistemas de resumen automático.']},stack:['Java · Hibernate','MySQL','OpenNLP · MetaMap','JDOM · PDFBox','Google API Language','Eclipse · Scrum · Mac OS X']}
];
const skillData=[
 {name:{en:'Backend & Python',es:'Backend y Python'},items:'Python · FastAPI · Django · Flask · SQLAlchemy · SQLModel',level:4},
 {name:{en:'APIs & architecture',es:'APIs y arquitectura'},items:'REST · OpenAPI · DDD · API integrations',level:4},
 {name:{en:'Testing & quality',es:'Pruebas y calidad'},items:'TDD · Unit testing · Integration testing',level:4},
 {name:{en:'Distributed systems',es:'Sistemas distribuidos'},items:'Async · Event-driven · Microservices · Celery · RabbitMQ',level:4},
 {name:{en:'Databases & modelling',es:'Bases de datos y modelado'},items:'PostgreSQL · MongoDB · ClickHouse · Redis · Data modelling',level:4},
 {name:{en:'Cloud & DevOps',es:'Cloud y DevOps'},items:'AWS · GCP · Azure · Docker · CI/CD · GitHub Actions · Jenkins',level:3},
 {name:{en:'Data engineering & ETL',es:'Ingeniería de datos y ETL'},items:'Dagster · Pandas · NumPy · Data pipelines',level:2},
 {name:{en:'Security & authentication',es:'Seguridad y autenticación'},items:'Authentication · Authorisation · Permissions',level:3},
 {name:{en:'Generative AI',es:'IA generativa'},items:'LLMs · RAG · Tool calling · Agents · AI infrastructure',level:1}
];
const jobs=document.querySelector('#jobs');
function renderJobs(lang){jobs.innerHTML=roles.map((r)=>`<details class="job"><summary><span class="job-period">${r.period}</span><span class="job-head"><h3 class="job-title">${r.title[lang]}</h3><span class="job-company">${r.company} <i>· ${r.location[lang]}</i></span></span><span class="job-sector">${r.sector[lang]}</span><span class="expand" aria-hidden="true"></span></summary><div class="job-details"><p class="job-summary">${r.summary[lang]}</p><ul>${r.bullets[lang].map(b=>`<li>${b}</li>`).join('')}</ul><div class="stack-label">${lang==='en'?'TECHNOLOGIES & STACK':'TECNOLOGÍAS Y STACK'}</div><div class="tech-tags">${r.stack.flatMap(t=>t.split(' · ')).map(t=>`<span>${t}</span>`).join('')}</div></div></details>`).join('')}
function renderSkills(lang){
 const ratings={en:['Base','Competent','Advanced','Expert'],es:['Inicial','Competente','Avanzado','Experto']};
 document.querySelector('#skillList').innerHTML=skillData.map(s=>{
  const rating=ratings[lang][s.level-1];
  const label=`${s.level}/4 - ${rating}`;
  const name=s.name[lang].replaceAll('&','&amp;');
  return `<article class="skill-row"><div class="skill-info"><h3>${s.name[lang]}</h3><div class="skill-techs">${s.items.split(' · ').map(item=>`<span>${item}</span>`).join('')}</div></div><div class="skill-meter-row"><div class="meter" role="progressbar" aria-label="${name}" aria-valuemin="0" aria-valuemax="4" aria-valuenow="${s.level}" aria-valuetext="${label}" title="${label}"><span class="meter-fill" style="width:${s.level*25}%"></span></div></div></article>`
 }).join('')
}
function setLanguage(lang,persist=true){document.documentElement.lang=lang;document.querySelectorAll('[data-en][data-es]').forEach(el=>{el.innerHTML=el.dataset[lang]});document.querySelectorAll('.lang-switch button').forEach(b=>{const active=b.dataset.lang===lang;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});document.title='Txema Bermúdez - Software Engineer';document.querySelector('.lang-switch').setAttribute('aria-label',lang==='es'?'Selector de idioma':'Language selector');document.querySelector('header nav[aria-label]').setAttribute('aria-label',lang==='es'?'Navegación principal':'Main navigation');applyTheme(document.documentElement.dataset.theme||'light');document.querySelectorAll('.social-linkedin').forEach(a=>{a.href=`https://www.linkedin.com/in/josemariabermudez/?locale=${lang==='es'?'es-ES':'en-US'}`;a.setAttribute('aria-label',lang==='es'?'Perfil de LinkedIn':'LinkedIn profile')});renderJobs(lang);renderSkills(lang);if(persist){try{localStorage.setItem('txb-lang-choice',lang)}catch(e){}}}
const themeToggle=document.querySelector('#themeToggle');
const systemTheme=window.matchMedia('(prefers-color-scheme: dark)');
let themePreference='system';
try{const savedTheme=localStorage.getItem('txb-theme');if(savedTheme==='dark'||savedTheme==='light')themePreference=savedTheme}catch(e){}
function applyTheme(theme){
 document.documentElement.dataset.theme=theme;
 const lang=document.documentElement.lang;
 const label=theme==='dark'?(lang==='es'?'Cambiar a modo claro':'Switch to light mode'):(lang==='es'?'Cambiar a modo oscuro':'Switch to dark mode');
 themeToggle.setAttribute('aria-label',label);themeToggle.title=label;
 const themeColor=document.querySelector('meta[name="theme-color"]');if(themeColor)themeColor.content=theme==='dark'?'#0c1424':'#101b35';
}
function syncTheme(){applyTheme(themePreference==='system'?(systemTheme.matches?'dark':'light'):themePreference)}
systemTheme.addEventListener('change',()=>{if(themePreference==='system')syncTheme()});
themeToggle.addEventListener('click',()=>{themePreference=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('txb-theme',themePreference)}catch(e){}syncTheme()});
document.querySelectorAll('.lang-switch button').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
syncTheme();
const preferredLanguage=(navigator.languages&&navigator.languages[0])||navigator.language||'';const normalizedLanguage=preferredLanguage.trim().toLowerCase();const browserPrefersSpanish=normalizedLanguage==='es'||normalizedLanguage.startsWith('es-')||normalizedLanguage.startsWith('es_')||normalizedLanguage==='spanish'||normalizedLanguage.startsWith('spanish ')||normalizedLanguage==='español'||normalizedLanguage.startsWith('español ');let language=browserPrefersSpanish?'es':'en';try{const savedLanguage=localStorage.getItem('txb-lang-choice');if(savedLanguage==='es'||savedLanguage==='en')language=savedLanguage}catch(e){}setLanguage(language,false);
